language: go
go:
- 1.x
trix:
  # I'm not sure why travis insists on running a build with os=linux and an empty
  # env but if it really wants to, let it, just don't make it fail our builds
  allow_failures:
   - os: linux
     env:
  # A true build matrix would be combinatorial - here we're only interested in
  # a few, specific build configurations.
  include:
   # at the time of this writing, travis has a semi-experimental osx option
   # builds run slower, but it's really handy because cross-compiling OSX
   # binaries got increasingly hard over the years
   - os: osx
     env: BROTLI_OS=darwin BROTLI_ARCH=amd64
   # thankfully, ubuntu 12.04 has a multilib variant of gcc readily available
   - os: linux
     env: BROTLI_OS=linux BROTLI_ARCH=386
     addons:
       apt:
         packages:
           - gcc-multilib
           - g++-multilib
   # binaries produced in this case run natively on the default travis config
   - os: linux
     env: BROTLI_OS=linux BROTLI_ARCH=amd64
   - os: linux
     env: BROTLI_OS=windows BROTLI_ARCH=386 TRIPLET=i686-w64-mingw32
     addons:
       apt:
         packages:
           # there's a meta-package but I could never get it to work on ubuntu 12.04
           # (current travis-ci linux distribution at the time of this commit)
           - gcc-mingw-w64-i686
           - g++-mingw-w64-i686
           - binutils-mingw-w64-i686
   - os: linux
     env: BROTLI_OS=windows BROTLI_ARCH=amd64 TRIPLET=x86_64-w64-mingw32
     addons:
       apt:
         packages:
           - gcc-mingw-w64-x86-64
           - g++-mingw-w64-x86-64
           - binutils-mingw-w64-x86-64
install:
- go get github.com/gorilla/feeds
- go get github.com/gorilla/mux
- go get github.com/mattn/go-sqlite3
- go get github.com/jinzhu/gorm
- go get github.com/lib/pq
- go get github.com/Sirupsen/logrus
- go get gopkg.in/natefinch/lumberjack.v2
- go get gopkg.in/gomail.v2
- go get github.com/gorilla/securecookie
- go get golang.org/x/crypto/bcrypt
- go get github.com/nicksnyder/go-i18n/i18n
- go build

script:
- go get github.com/mitchellh/gox
- go get github.com/tcnksm/ghr
- go get github.com/axw/gocov/gocov
- gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
- ghr --username ewhal --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
