language: go
go:
- 1.x
install:
- sudo curl http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | sudo apt-key add -
- sudo apt-get install -y cross-gcc-dev cross-binutils 
- sudo apt-get install gcc-mingw-w64
- go get github.com/gorilla/feeds
- go get github.com/gorilla/mux
- go get github.com/mattn/go-sqlite3
- go get github.com/jinzhu/gorm
- go get github.com/lib/pq
- go get github.com/Sirupsen/logrus
- go get gopkg.in/natefinch/lumberjack.v2
- go get gopkg.in/gomail.v2
- go get github.com/gorilla/securecookie
- go get golang.org/x/crypto/bcrypt
- go get github.com/nicksnyder/go-i18n/i18n
- go build

script:
- go get github.com/mitchellh/gox
- go get github.com/tcnksm/ghr
- go get github.com/axw/gocov/gocov
- gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
- ghr --username ewhal --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
